"""
setup_env.py — Interactive helper to create your .env file safely.

Run this ONCE to generate your .env from the template.
It will prompt you for API keys and write them to .env.

Run:
    python setup_env.py
"""

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.resolve()
ENV_EXAMPLE = PROJECT_ROOT / ".env.example"
ENV_FILE = PROJECT_ROOT / ".env"


def main():
    print("=" * 60)
    print("  adversarial-rag-soc — Environment Setup")
    print("=" * 60)
    print()

    if ENV_FILE.exists():
        print(f"[WARNING] .env already exists at: {ENV_FILE}")
        overwrite = input("Overwrite it? (y/N): ").strip().lower()
        if overwrite != "y":
            print("Aborted. Your existing .env was not changed.")
            sys.exit(0)

    print("We'll set up your .env file now.")
    print("Press ENTER to skip any key you don't have yet.")
    print()

    # ── Provider selection ────────────────────────────────────────
    print("Which LLM provider do you want to use for Phase 0-3?")
    print("  1. Groq (FREE — recommended for now)")
    print("  2. Anthropic (Claude Haiku — paid)")
    print("  3. OpenAI (GPT-4o-mini — paid)")
    choice = input("Enter 1, 2, or 3 [default: 1]: ").strip() or "1"

    provider_map = {"1": "groq", "2": "anthropic", "3": "openai"}
    model_map = {
        "1": "llama-3.1-8b-instant",
        "2": "claude-haiku-3-5",
        "3": "gpt-4o-mini",
    }
    provider = provider_map.get(choice, "groq")
    model = model_map.get(choice, "llama-3.1-8b-instant")

    print()
    print(f"Selected: {provider} / {model}")
    print()

    # ── API key input ─────────────────────────────────────────────
    groq_key = ""
    anthropic_key = ""
    openai_key = ""

    if provider == "groq":
        print("Get your free Groq key at: https://console.groq.com/")
        groq_key = input("GROQ_API_KEY: ").strip()
    elif provider == "anthropic":
        print("Get your Anthropic key at: https://console.anthropic.com/")
        anthropic_key = input("ANTHROPIC_API_KEY: ").strip()
    elif provider == "openai":
        print("Get your OpenAI key at: https://platform.openai.com/")
        openai_key = input("OPENAI_API_KEY: ").strip()

    # ── Write .env ────────────────────────────────────────────────
    env_content = f"""# Auto-generated by setup_env.py — DO NOT COMMIT THIS FILE
# Run setup_env.py again to regenerate.

# ============================================================
# LLM API KEYS
# ============================================================
GROQ_API_KEY={groq_key}
ANTHROPIC_API_KEY={anthropic_key}
OPENAI_API_KEY={openai_key}

# ============================================================
# MODEL SELECTION
# ============================================================
LLM_MODEL={model}
LLM_PROVIDER={provider}

# Cheap model for defense LLM calls (Phase 8)
DEFENSE_LLM_MODEL=llama-3.1-8b-instant
DEFENSE_LLM_PROVIDER=groq

# ============================================================
# PATH CONFIGURATION
# ============================================================
CHROMA_CLEAN_PATH=data/chroma_clean
CHROMA_POISONED_PATH=data/chroma_poisoned
CLEAN_ALERTS_PATH=data/alerts/clean_alerts.json
SUSPICIOUS_QUEUE_PATH=data/alerts/suspicious_queue.json
EVAL_FIXED_SET_PATH=data/alerts/eval_fixed_set.json

# ============================================================
# PIPELINE CONFIGURATION
# ============================================================
MAX_ALERTS=1000
RETRIEVAL_TOP_K=3
DEFENSE_ACTIVE=false
"""

    with open(ENV_FILE, "w", encoding="utf-8") as f:
        f.write(env_content)

    print()
    print(f"[OK] .env created at: {ENV_FILE}")
    print()
    print("Next step: Run the hello world verification:")
    print("  python ingestion/hello_world.py")
    print()
    print("[REMINDER] Never commit .env — it contains your API keys.")


if __name__ == "__main__":
    main()
